// <auto-generated />
namespace Chat_Room_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChatMessage_MessageIsRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChatMessage_MessageIsRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201805081716515_ChatMessage_MessageIsRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
